GENDER_MALE     = 0
GENDER_FEMALE   = 1

NODE_TYPE_GROUND = 2
NODE_TYPE_AIR = 3
NODE_TYPE_CLIMB = 4
NODE_TYPE_WATER = 5

ORDER_ATTACK        = 1
ORDER_ATTACKMOVE    = 2
ORDER_MOVE          = 3
ORDER_STOP          = 4

ROUND_WAITING   = 1
ROUND_PREPARING = 2
ROUND_SETUP     = 3
ROUND_STARTED   = 4
ROUND_ENDED     = 5

TASK_FLASH_NONE     = 0
TASK_FLASH_ACTIVATE = 1
TASK_FLASH_ABORT    = 2
TASK_FLASH_COMPLETE = 3

TEAM_SPECTATOR      = 1
TEAM_OVERWATCH      = 2
TEAM_REBELS         = 3
TEAM_COMBINE        = 4

VOICE_HELP      = 1
VOICE_MEDIC     = 2
VOICE_CHEER     = 3
VOICE_LEAD      = 4
VOICE_GO        = 5
VOICE_READY     = 6
VOICE_WARN      = 7
VOICE_QUESTION  = 8
VOICE_ANSWER    = 9
VOICE_RELOAD    = 10
VOICE_HEAL      = 11