GM.Relationships = {
    default = {
        --Combine
        npc_clawscanner         = D_HT,
        npc_combine_camera      = D_HT,
        npc_combine_s           = D_HT,
        npc_combinedropship     = D_HT,
        npc_combinegunship      = D_HT,
        npc_cscanner            = D_HT,
        npc_helicopter          = D_HT,
        npc_hunter              = D_HT,
        npc_manhack             = D_HT,
        npc_metropolice         = D_HT,
        npc_rollermine          = D_HT,
        npc_stalker             = D_HT,
        npc_strider             = D_HT,
        npc_turret_ceiling      = D_HT,
        npc_turret_floor        = D_HT,

        --Aliens & Zombies
        npc_antlion             = D_HT,
        npc_antlion_worker      = D_HT,
        npc_antlionguard        = D_HT,
        npc_barnacle            = D_HT,
        npc_fastzombie          = D_HT,
        npc_fastzombie_torso    = D_HT,
        npc_headcrab            = D_HT,
        npc_headcrab_black      = D_HT,
        npc_headcrab_fast       = D_HT,
        npc_headcrab_poison     = D_HT,
        npc_poisonzombie        = D_HT,
        npc_zombie              = D_HT,
        npc_zombie_torso        = D_HT,
        npc_zombine             = D_HT,

        --Humans
        npc_alyx        = D_LI,
        npc_barney      = D_LI,
        npc_breen       = D_NU,
        npc_citizen     = D_LI,
        npc_dog         = D_LI,
        npc_eli         = D_LI,
        npc_gman        = D_NU,
        npc_kleiner     = D_LI,
        npc_magnusson   = D_LI,
        npc_monk        = D_LI,
        npc_mossman     = D_LI,
        npc_vortigaunt  = D_LI,

        --Other
        npc_crow    = D_HT,
        npc_pigeon  = D_HT,
        npc_seagull = D_HT
    },
    combine = {
        --Combine
        npc_clawscanner         = D_LI,
        npc_combine_camera      = D_LI,
        npc_combine_s           = D_LI,
        npc_combinedropship     = D_LI,
        npc_combinegunship      = D_LI,
        npc_cscanner            = D_LI,
        npc_helicopter          = D_LI,
        npc_hunter              = D_LI,
        npc_manhack             = D_LI,
        npc_metropolice         = D_LI,
        npc_rollermine          = D_LI,
        npc_stalker             = D_LI,
        npc_strider             = D_LI,
        npc_turret_ceiling      = D_LI,
        npc_turret_floor        = D_LI,

        --Humans
        npc_alyx        = D_HT,
        npc_barney      = D_HT,
        npc_citizen     = D_HT,
        npc_dog         = D_HT,
        npc_eli         = D_HT,
        npc_kleiner     = D_HT,
        npc_magnusson   = D_HT,
        npc_monk        = D_HT,
        npc_mossman     = D_HT,
        npc_vortigaunt  = D_HT,
    },
}