GM.VoiceLines = {
    --VOICE_HELP
    {
        male = {
            "vo/npc/male01/help01.wav"
        },
        female = {
            "vo/npc/female01/help01.wav"
        }
    },
    --VOICE_MEDIC
    {
        male = {
            "vo/npc/male01/imhurt01.wav",
            "vo/npc/male01/imhurt02.wav",
            "vo/npc/male01/myarm01.wav",
            "vo/npc/male01/myarm02.wav",
            "vo/npc/male01/mygut02.wav",
            "vo/npc/male01/myleg01.wav",
            "vo/npc/male01/myleg02.wav"
        },
        female = {
            "vo/npc/female01/imhurt01.wav",
            "vo/npc/female01/imhurt02.wav",
            "vo/npc/female01/myarm01.wav",
            "vo/npc/female01/myarm02.wav",
            "vo/npc/female01/mygut02.wav",
            "vo/npc/female01/myleg01.wav",
            "vo/npc/female01/myleg02.wav"
        }
    },
    --VOICE_CHEER
    {
        male = {
            "vo/npc/male01/evenodds.wav",
            "vo/npc/male01/fantastic01.wav",
            "vo/npc/male01/fantastic02.wav",
            "vo/npc/male01/gotone01.wav",
            "vo/npc/male01/gotone02.wav",
            "vo/npc/male01/yeah02.wav",
            "vo/npc/male01/yougotit02.wav"
        },
        female = {
            "vo/npc/female01/fantastic01.wav",
            "vo/npc/female01/fantastic02.wav",
            "vo/npc/female01/gotone01.wav",
            "vo/npc/female01/gotone02.wav",
            "vo/npc/female01/yeah02.wav",
            "vo/npc/female01/yougotit02.wav"
        }
    },
    --VOICE_LEAD
    {
        male = {
            "vo/npc/male01/leadtheway01.wav",
            "vo/npc/male01/leadtheway02.wav"
        },
        female = {
            "vo/npc/female01/leadtheway01.wav",
            "vo/npc/female01/leadtheway02.wav"
        }
    },
    --VOICE_GO
    {
        male = {
            "vo/npc/male01/letsgo01.wav",
            "vo/npc/male01/letsgo02.wav"
        },
        female = {
            "vo/npc/female01/letsgo01.wav",
            "vo/npc/female01/letsgo02.wav"
        }
    },
    --VOICE_READY
    {
        male = {
            "vo/npc/male01/ok01.wav",
            "vo/npc/male01/ok02.wav",
            "vo/npc/male01/okimready01.wav",
            "vo/npc/male01/okimready02.wav",
            "vo/npc/male01/okimready03.wav"
        },
        female = {
            "vo/npc/female01/ok01.wav",
            "vo/npc/female01/ok02.wav",
            "vo/npc/female01/okimready01.wav",
            "vo/npc/female01/okimready02.wav",
            "vo/npc/female01/okimready03.wav"
        }
    },
    --VOICE_WARN
    {
        male = {
            "vo/npc/male01/behindyou01.wav",
            "vo/npc/male01/behindyou02.wav",
            "vo/npc/male01/headsup01.wav",
            "vo/npc/male01/headsup02.wav",
            "vo/npc/male01/runforyourlife01.wav",
            "vo/npc/male01/runforyourlife02.wav",
            "vo/npc/male01/runforyourlife03.wav",
            "vo/npc/male01/strider_run.wav",
            "vo/npc/male01/takecover02.wav",
            "vo/npc/male01/watchout.wav"
        },
        female = {
            "vo/npc/female01/behindyou01.wav",
            "vo/npc/female01/behindyou02.wav",
            "vo/npc/female01/headsup01.wav",
            "vo/npc/female01/headsup02.wav",
            "vo/npc/female01/runforyourlife01.wav",
            "vo/npc/female01/runforyourlife02.wav",
            "vo/npc/female01/strider_run.wav",
            "vo/npc/female01/takecover02.wav",
            "vo/npc/female01/watchout.wav"
        }
    },
    --VOICE_QUESTION
    {
        male = {
            "vo/npc/male01/question01.wav",
            "vo/npc/male01/question02.wav",
            "vo/npc/male01/question03.wav",
            "vo/npc/male01/question04.wav",
            "vo/npc/male01/question05.wav",
            "vo/npc/male01/question06.wav",
            "vo/npc/male01/question07.wav",
            "vo/npc/male01/question08.wav",
            "vo/npc/male01/question09.wav",
            "vo/npc/male01/question10.wav",
            "vo/npc/male01/question11.wav",
            "vo/npc/male01/question12.wav",
            "vo/npc/male01/question13.wav",
            "vo/npc/male01/question14.wav",
            "vo/npc/male01/question15.wav",
            "vo/npc/male01/question16.wav",
            "vo/npc/male01/question17.wav",
            "vo/npc/male01/question18.wav",
            "vo/npc/male01/question19.wav",
            "vo/npc/male01/question20.wav",
            "vo/npc/male01/question21.wav",
            "vo/npc/male01/question22.wav",
            "vo/npc/male01/question23.wav",
            "vo/npc/male01/question24.wav",
            "vo/npc/male01/question25.wav",
            "vo/npc/male01/question26.wav",
            "vo/npc/male01/question27.wav",
            "vo/npc/male01/question28.wav",
            "vo/npc/male01/question29.wav",
            "vo/npc/male01/question30.wav",
            "vo/npc/male01/question31.wav"
        },
        female = {
            "vo/npc/female01/question01.wav",
            "vo/npc/female01/question02.wav",
            "vo/npc/female01/question03.wav",
            "vo/npc/female01/question04.wav",
            "vo/npc/female01/question05.wav",
            "vo/npc/female01/question06.wav",
            "vo/npc/female01/question07.wav",
            "vo/npc/female01/question08.wav",
            "vo/npc/female01/question09.wav",
            "vo/npc/female01/question10.wav",
            "vo/npc/female01/question11.wav",
            "vo/npc/female01/question12.wav",
            "vo/npc/female01/question13.wav",
            "vo/npc/female01/question14.wav",
            "vo/npc/female01/question15.wav",
            "vo/npc/female01/question16.wav",
            "vo/npc/female01/question17.wav",
            "vo/npc/female01/question18.wav",
            "vo/npc/female01/question19.wav",
            "vo/npc/female01/question20.wav",
            "vo/npc/female01/question21.wav",
            "vo/npc/female01/question22.wav",
            "vo/npc/female01/question23.wav",
            "vo/npc/female01/question24.wav",
            "vo/npc/female01/question25.wav",
            "vo/npc/female01/question26.wav",
            "vo/npc/female01/question27.wav",
            "vo/npc/female01/question28.wav",
            "vo/npc/female01/question29.wav",
            "vo/npc/female01/question30.wav"
        }
    },
    --VOICE_ANSWER
    {
        male = {
            "vo/npc/male01/answer01.wav",
            "vo/npc/male01/answer02.wav",
            "vo/npc/male01/answer03.wav",
            "vo/npc/male01/answer04.wav",
            "vo/npc/male01/answer05.wav",
            "vo/npc/male01/answer07.wav",
            "vo/npc/male01/answer08.wav",
            "vo/npc/male01/answer09.wav",
            "vo/npc/male01/answer10.wav",
            "vo/npc/male01/answer11.wav",
            "vo/npc/male01/answer12.wav",
            "vo/npc/male01/answer13.wav",
            "vo/npc/male01/answer14.wav",
            "vo/npc/male01/answer15.wav",
            "vo/npc/male01/answer16.wav",
            "vo/npc/male01/answer17.wav",
            "vo/npc/male01/answer18.wav",
            "vo/npc/male01/answer19.wav",
            "vo/npc/male01/answer20.wav",
            "vo/npc/male01/answer21.wav",
            "vo/npc/male01/answer22.wav",
            "vo/npc/male01/answer22.wav",
            "vo/npc/male01/answer24.wav",
            "vo/npc/male01/answer25.wav",
            "vo/npc/male01/answer26.wav",
            "vo/npc/male01/answer27.wav",
            "vo/npc/male01/answer28.wav",
            "vo/npc/male01/answer29.wav",
            "vo/npc/male01/answer30.wav",
            "vo/npc/male01/answer31.wav",
            "vo/npc/male01/answer32.wav",
            "vo/npc/male01/answer33.wav",
            "vo/npc/male01/answer34.wav",
            "vo/npc/male01/answer35.wav",
            "vo/npc/male01/answer36.wav",
            "vo/npc/male01/answer37.wav",
            "vo/npc/male01/answer38.wav",
            "vo/npc/male01/answer39.wav",
            "vo/npc/male01/answer40.wav"
        },
        female = {
            "vo/npc/female01/answer01.wav",
            "vo/npc/female01/answer02.wav",
            "vo/npc/female01/answer03.wav",
            "vo/npc/female01/answer04.wav",
            "vo/npc/female01/answer05.wav",
            "vo/npc/female01/answer07.wav",
            "vo/npc/female01/answer08.wav",
            "vo/npc/female01/answer09.wav",
            "vo/npc/female01/answer10.wav",
            "vo/npc/female01/answer11.wav",
            "vo/npc/female01/answer12.wav",
            "vo/npc/female01/answer13.wav",
            "vo/npc/female01/answer14.wav",
            "vo/npc/female01/answer15.wav",
            "vo/npc/female01/answer16.wav",
            "vo/npc/female01/answer17.wav",
            "vo/npc/female01/answer18.wav",
            "vo/npc/female01/answer19.wav",
            "vo/npc/female01/answer20.wav",
            "vo/npc/female01/answer21.wav",
            "vo/npc/female01/answer22.wav",
            "vo/npc/female01/answer22.wav",
            "vo/npc/female01/answer24.wav",
            "vo/npc/female01/answer25.wav",
            "vo/npc/female01/answer26.wav",
            "vo/npc/female01/answer27.wav",
            "vo/npc/female01/answer28.wav",
            "vo/npc/female01/answer29.wav",
            "vo/npc/female01/answer30.wav",
            "vo/npc/female01/answer31.wav",
            "vo/npc/female01/answer32.wav",
            "vo/npc/female01/answer33.wav",
            "vo/npc/female01/answer34.wav",
            "vo/npc/female01/answer35.wav",
            "vo/npc/female01/answer36.wav",
            "vo/npc/female01/answer37.wav",
            "vo/npc/female01/answer38.wav",
            "vo/npc/female01/answer39.wav",
            "vo/npc/female01/answer40.wav"
        }
    },
    --VOICE_RELOAD
    {
        male = {
            "vo/npc/male01/coverwhilereload01.wav",
            "vo/npc/male01/coverwhilereload02.wav",
            "vo/npc/male01/gottareload01.wav"
        },
        female = {
            "vo/npc/female01/coverwhilereload01.wav",
            "vo/npc/female01/coverwhilereload02.wav",
            "vo/npc/female01/gottareload01.wav"
        }
    },
    --VOICE_HEAL
    {
        male = {
            "vo/npc/male01/health01.wav",
            "vo/npc/male01/health02.wav",
            "vo/npc/male01/health03.wav",
            "vo/npc/male01/health04.wav",
            "vo/npc/male01/health05.wav"
        },
        female = {
            "vo/npc/female01/health01.wav",
            "vo/npc/female01/health02.wav",
            "vo/npc/female01/health03.wav",
            "vo/npc/female01/health04.wav",
            "vo/npc/female01/health05.wav",
        }
    }
}